### PR TITLE
fix: update python api-cors-lambda 

### LINKED ISSUE #381: python api-cors-lambda out of date
### What is the problem?
The python `api-cors-lambda` is out of date. https://github.com/aws/aws-cdk/pull/4211 makes it much more straightforward to enable CORS on a REST API endpoint. The example code should be updated to reflect that.

### PR DESCRIPTION
**Pull request by alex9311**
The python api-cors-lambda example is out of date. aws/aws-cdk#4211 makes it much more straightforward to enable CORS on a REST API endpoint. I've updated the example code  to use `default_cors_preflight_options` 

Fixes #381

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by alex9311** [comment]
hey @NGL321 I saw you were assigned to this PR, any chance I could get a quick review and approval? Thanks!

**Review by NGL321 — APPROVED** [review]
Thank you for contributing @alex9311! This looks excellent, I have no further suggestions.

**Comment by alex9311** [comment]
> Thank you for contributing @alex9311! This looks excellent, I have no further suggestions.

Thanks @NGL321 ! Looks like I need an approval in order to merge :)

**Review by peterwoodworth — DISMISSED** [review]

**Comment by alex9311** [comment]
ar @peterwoodworth thanks for the approval. Had to merge master into my branch to be allowed to merge which invalidated your approval

**Comment by peterwoodworth** [comment]
Sorry for the long delay here @alex9311, thanks for your patience 🙏

**Comment by peterwoodworth** [comment]
By the way, don't merge master into your branch manually, the automation will handle it

**Review by peterwoodworth — APPROVED** [review]

**Pull request merged**
