### PR TITLE
feat: python vpc

### PR DESCRIPTION
**Pull request by josjaf**
Fixes # 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by richardhboyd** [comment]
This should have a README that explains what the example is doing

**Comment by josjaf** [comment]
Okay, I've added a readme, should I send another PR?

**Comment by josjaf** [comment]
responded to feedback

**Comment by josjaf** [comment]
can somebody please review?

**Comment by rhboyd** [comment]
Can you message me on Chime to discuss this PR. rhboyd@

**Comment by indrora** [comment]
This PR has not been touched since before the release of CDKv2. Closing.

**Pull request closed without merging**
