### PR TITLE
feat: Add Golang samples to build

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Fixes # 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by gliptak** [comment]
@ryparker please review

**Comment by ryparker** [comment]
Would you mind providing a general rundown of the changes made? I'm still learning Go so any context would give me a boost. 😄

**Comment by gliptak** [comment]
certainly
+ added scaffolding to check updates to the tree and trigger compile + sync
+ bumped several `Go` dependency versions (and associated checksums)
+ updated with `default` section (based on `aws-cdk-go` API change

**Comment by gliptak** [comment]
@ryparker are there additional changes for this PR?

**Pull request closed without merging**
