### PR TITLE
feat(Typescript): Microsoft Active Directory + FSx for Windows File Server example

### PR DESCRIPTION
**Pull request by javydekoning**
Added examples in the Typescript language for creating an FSx for Windows File Server filesystem which is joined to an Managed Microsoft Active Directory in AWS.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by ryparker** [comment]
Thanks for contributing this. Testing this now.

**Comment by ryparker** [comment]
I was able to build the stack however I'd like to add something that demos how to use the AD rather than just how to standup the AD.

**Comment by javydekoning** [comment]
Hi Ryan, any suggestions? For example,I could ad join an FSx filesystem?

**Review by ryparker — APPROVED** [review]
I think that this example is good to merge as is. We can add other features to the example as needed.

**Pull request merged**
