### PR TITLE
fix: updates to ec2 Example

### PR DESCRIPTION
**Pull request by schuettc**
This changes updates an older example for creating an EC2 instance and includes examples for using UserData and CloudInit.  This also includes an option for configuring SSH.

Fixes #

https://github.com/aws-samples/aws-cdk-examples/issues/853

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Review by ericzbeard — COMMENTED** [review]
This looks great, can you go back through and add code comments above classes, functions, and code blocks? This will make it easier for people to understand the example, and also make better food for generative AI training.

**Comment by schuettc** [comment]
Updated with comments

**Review by ericzbeard — APPROVED** [review]

**Comment by ericzbeard** [comment]
Not sure why this PR isn't merging...

**Review by mmaeng — APPROVED** [review]

**Comment by mmaeng** [comment]
Looks like the process just had to get kicked for the statuses to report back correctly.

**Pull request merged**
