### PR TITLE
feat: Add example for batch-compute-with-step-functions

### PR DESCRIPTION
**Pull request by hy714335634**
<!--
add python example:batch-compute-with-step-functions
services:AWS Batch, AWS Stepfunctions, AWS Fargate, CI/CD Pipeline(AWS Code*)
---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by hy714335634** [comment]
Is there anyone can review this request?

**Comment by ryparker** [comment]
Looks like a compatibility error is being thrown in CI:

```sh
ERROR: aws-cdk-core 1.124.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.5 which is incompatible.
ERROR: aws-cdk-assets 1.124.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.5 which is incompatible
```

**Comment by hy714335634** [comment]
> Looks like a compatibility error is being thrown in CI:
> 
> ```shell
> ERROR: aws-cdk-core 1.124.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.5 which is incompatible.
> ERROR: aws-cdk-assets 1.124.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.5 which is incompatible
> ```

This is build on lower version of cdk, I will double check it on the latest cdk

**Comment by indrora** [comment]
This PR is well into a year old, has merge conflicts, and doesn't build. I'm closing it.

**Pull request closed without merging**
