### PR TITLE
docs(readme): fix typo

### PR DESCRIPTION
**Pull request by appwiz**
Fix a typo in the README (s/Awsome/Awesome). No issue exists.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Review by skinny85 — APPROVED** [review]
Thanks for the contribution @appwiz!

**Comment by SoManyHs** [comment]
@mergifyio refresh

**Comment by ryparker** [comment]
@Mergifyio update

**Comment by ryparker** [comment]
@Mergifyio rebase

**Comment by ryparker** [comment]
Branch no longer exists. Closing in favor of https://github.com/aws-samples/aws-cdk-examples/pull/462

**Pull request closed without merging**
