### PR TITLE
feat: Add (sample) generated diagrams

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Fixes # 

Generation steps

```
npm install @mhlabs/cfn-diagram
npx cfn-dia draw.io --ci-mode
drawio --output diagram.png --export template.drawio
```

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by gliptak** [comment]
@ryparker please review

**Review by ryparker — APPROVED** [review]
Nice to have some visuals. Thanks for the contribution 💯

**Comment by gliptak** [comment]
@ryparker do you see this as individual/manual generation or possibly generated on PRs and published for `master` commits?

**Comment by ryparker** [comment]
> @ryparker do you see this as individual/manual generation or possibly generated on PRs and published for `master` commits?

I like the idea of having design visuals generated automatically from CI on PR commits. If you do happen to open a PR for that automation, would you be able to adjust the presentation of the resource ids? What do you think about replacing the ids with the resource name to make things a little clearer and prevent overlap?

Otherwise I think individual/manual contributions of visuals would be nice.

**Comment by gliptak** [comment]
@ryparker those names are based on (randomized) resource names in `synth` output

**Pull request merged**
