### PR TITLE
feat(new-ex): add AppSync triggering Event Bridge Example

### PR DESCRIPTION
**Pull request by awsed**
I'd like to add a sample I created that sends events to Event Bridge via an AppSync GraphQL API

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by awsed** [comment]
Any ETA on when this is going to be merged? It's been 4 months since the pull request

**Comment by NGL321** [comment]
@awsed When I gave this a review Thursday, it did not build. I just updated the package build info so that it should build properly so I can merge it today.

I am sorry there has been so much delay on this, moving forward we hope to have better turn around time merging new examples.

**Comment by awsed** [comment]
@NGL321 looks like it still hasn't built, are there any issues with the PR?

**Comment by NGL321** [comment]
@awsed Looks like this is unfortunately blocked by #216 for the moment. Pushing a fix

**Pull request merged**
