### PR TITLE
Add an example for API Gateway with CORS, and CRUD Lambdas with DynamoDB

### PR DESCRIPTION
**Pull request by simalexan**
*Issue #, if available:*
There wasn't an example demonstrating how to use API Gateway (CORS) pointing to multiple Lambda's which are doing CRUD operations over a DynamoDB table.

*Description of changes:*
Add a AWS CDK example for API Gateway with CORS, and CRUD Lambdas with DynamoDB. There are different Lambdas doing Create an Item, Get Item, Get All Items, Update Item and Delete Item.

Should be useful for developers starting with AWS CDK on how to run an API with Lambdas and DynamoDB. Additionally it shows off the current way of doing CORS on API GW with AWS CDK.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rix0rrr** [comment]
That looks great, thanks!

Would you mind spending a couple more minutes writing a short README for your example, and then adding a link to the top-level README directory?

**Comment by simalexan** [comment]
Thank you! Sure, will do that!

**Comment by simalexan** [comment]
@rix0rrr Done! Hope it suffices.

By the way, I'd be more than interested into jointly defining a broad example README template for the these AWS CDK examples, so that developers can contribute easier to this repository.

**Comment by rix0rrr** [comment]
Yes, especially for more complex examples I think a README would help. Would you mind trying your hand at defining a template? I would love it.

I think we can skip the "how to use CDK" instructions, maybe talk more about what the example defines and how it defines it (construct structure, parameters, and such).

In the mean time, more than happy to merge this.

**Pull request merged**
