### PR TITLE
Opensearch Cluster in VPC and authenticated access to dashboard outside VPC using Nginx Proxy server

### PR DESCRIPTION
**Pull request by deshruch**
Opensearch Cluster in VPC and authenticated access to dashboard outside VPC using Nginx Proxy server
This project demonstrates how to set up Amazon OpenSearch Service domain in a VPC. Along with OpenSearch Service domain it also launches an EC2 instance to run nginx proxy for accessing OpenSearch Dashboards.
This example also deploys Cognito resources to provide authenticated access to Amazon Opensearch Dashboard.

Fixes # [Issue917](https://github.com/aws-samples/aws-cdk-examples/issues/917)

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by kaizio** [comment]
Thanks @deshruch for the contribution. The following typescript/opensearch/os_vpc_provision/jest.config.js file is causing your app to fail the build. Please delete this file since you don't have any test for it to run.

**Comment by deshruch** [comment]
@kaizio will do.. thanks

**Comment by deshruch** [comment]
@kaizio Done. Can you review please?

**Review by kaizio — COMMENTED** [review]
:+1:

**Review by kaizio — APPROVED** [review]

**Comment by deshruch** [comment]
@kaizio Thank you!

**Comment by peternied** [comment]
@deshruch Nicely done - OpenSearch has some CDK projects of its own that might overlap with this contribution or alternately be useful to include in this repository.  I've created an issue within the OpenSearch-Project to follow up [1] and potentially build off this change.

- [1] https://github.com/opensearch-project/opensearch-cluster-cdk/issues/89

**Comment by deshruch** [comment]
> @deshruch Nicely done - OpenSearch has some CDK projects of its own that might overlap with this contribution or alternately be useful to include in this repository. I've created an issue within the OpenSearch-Project to follow up [1] and potentially build off this change.
> 
> * [1] [Relationship between aws-cdk-examples and this repository opensearch-project/opensearch-cluster-cdk#89](https://github.com/opensearch-project/opensearch-cluster-cdk/issues/89)

Makes sense. TBH, I was not aware of the other repo you mentioned, so I guess it does need some exposure

**Pull request merged**
