### PR TITLE
chore: Add snippet extraction workflows and scripts

### PR DESCRIPTION
**Pull request by Jerry-AWS**
Add snippet extraction workflows and scripts. See .github/extract-snippets/README.md for details.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by Jerry-AWS** [comment]
@NGL321 I've put what I consider the final touches on this PR, including a "dry run" workflow to check that PRs have good snippet hygiene. Review at your convenience.

**Comment by Jerry-AWS** [comment]
Just realized that extracting snippets only from the files in a given push leaves the repo open to consistency problems (e.g. same snippets defined in two different files). The only way to avoid that is to always scan the entire repo.

**Comment by Jerry-AWS** [comment]
OK, address that; ready for review.

**Comment by Jerry-AWS** [comment]
@NGL321 The SDK code examples team needed a way to find errors in their snippets, and so I pressed this into service. In the process I fixed some bugs, improved error handling, and added additional reporting that will be helpful in maintaining the snippets. And so here's the new version for the CDK examples as well.

**Review by NGL321 — DISMISSED** [review]

**Review by ryparker — APPROVED** [review]

**Pull request merged**
