### PR TITLE
fix: removed space from end of filename

### LINKED ISSUE #693: Trailing space in filename preventing checkout on WINDOWS
### Describe the bug

Can't checkout on Windows

### Expected Behavior

succesfull checkout

### Current Behavior

git checkout master

results in: 
error: invalid path 'typescript/s3-kms-cross-account-replication/.prettierignore '

### Reproduction Steps

try and clone the repo on windows

### Possible Solution

rename the file and remove the trailing space

'typescript/s3-kms-cross-account-replication/.prettierignore '

### Additional Information/Context

_No response_

### CDK CLI Version

2.28.1

### Framework Version

_No response_

### Node.js Version

18.4.0

### OS

windows 11

### Language

Typescript

### Language Version

_No response_

### PR DESCRIPTION
**Pull request by stowg**
remove a trailing space in filename (preventing checkout on Windows)

Fixes #693 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Review by peterwoodworth — APPROVED** [review]
thanks!

**Comment by saurabhagrawal86** [comment]
This issue is still happening on Windows. Please approve the PR and merge your changes soon. 

Following error message is being thrown at the moment: 
`
$ git clone https://github.com/aws-samples/aws-cdk-examples.git
Cloning into 'aws-cdk-examples'...
remote: Enumerating objects: 5635, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 5635 (delta 25), reused 67 (delta 16), pack-reused 5528
Receiving objects: 100% (5635/5635), 55.48 MiB | 2.87 MiB/s, done.
Resolving deltas: 100% (2921/2921), done.
error: invalid path 'typescript/s3-kms-cross-account-replication/.prettierignore '
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
`

**Comment by peterwoodworth** [comment]
Thanks @saurabhagrawal86, I thought this would have merged when I approved last time, maybe our automation has been modified. Regardless, will ensure this gets merged soon

**Review by peterwoodworth — DISMISSED** [review]

**Comment by stowg** [comment]
@peterwoodworth  I think we need you to approve again? 
It was out-of-date from MASTER - now I'm getting:
_"First-time contributors need a maintainer to approve running workflows..."_

**Review by peterwoodworth — APPROVED** [review]

**Pull request merged**
