### PR TITLE
feat(python): adding AWS Batch examples

### PR DESCRIPTION
**Pull request by awsvikrant**
AWS Batch example using python CDK.

Fixes # 

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by awsvikrant** [comment]
AWS Batch using python CDK for EC2 instance type
AWS Batch using python CDK for ARM64 instance type.

**Comment by awsvikrant** [comment]
Changed pull request as per requirement.

**Comment by awsvikrant** [comment]
Updated code for cdk 2.0.0

**Comment by awsvikrant** [comment]
Adding only Batch with Fargate example.

**Comment by awsvikrant** [comment]
Adding EC2 SPOT and ARM64 base instance type example.

**Review by MrArnoldPalmer — DISMISSED** [review]

**Pull request merged**
