### PR TITLE
feat: api gateway lambda auth

### PR DESCRIPTION
**Pull request by Me-Sunil**
**What is the Change ?**

_Creating a comprehensive CDK (AWS Cloud Development Kit) example for integrating a Lambda-based REST API Gateway with a tokenizing Lambda authentication mechanism represents a pivotal step towards establishing a secure, scalable, and efficient cloud-native architecture._

**Why this example is important ?** 

_People struggle with integrating authorizer in API gateway, because it may bring unforeseen challenges like -_ 

- Integration Errors: Coordinating the integration of various services and ensuring seamless communication can be challenging. Issues related to connecting different components, setting up appropriate permissions, and handling error scenarios might arise, causing integration roadblocks.
- Tokenization Logic: Creating a robust tokenization logic and integrating it seamlessly with the authentication flow can be intricate. Incorrect token generation, validation, or handling of authorization can result in security vulnerabilities or access control problems.

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Comment by kaizio** [comment]
@Me-Sunil Thanks for the contribution! If you don't mind could you change the imports to match cdk v2 convention for ts. Also please add a README.md to explain how to run the cdk app and what it is accomplishing.

**Comment by Me-Sunil** [comment]
Hi @kaizio,
Based on Feedback, recent changes contains
- [x] Refactor Imports based on cdk v2
- [x] ReadMe, to explain what pattern is and how to execute it.

**Comment by Me-Sunil** [comment]
Hi @kaizio, can you let me know what is the progress on this.

**Review by kaizio — APPROVED** [review]

**Review by kaizio — APPROVED** [review]
LGTM

**Pull request merged**
