### PR TITLE
CDK General Availability (1.0.0) updates

### PR DESCRIPTION
**Pull request by skinny85**
Fix examples for CDK's General Availability (1.0.0) release.

----------

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by skinny85** [comment]
We're getting closer...the Java build is succeeding, now only Python is left ;)

**Comment by rix0rrr** [comment]
```
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.


```

**Comment by rix0rrr** [comment]
Aha, python3.6 is only available starting from Ubuntu 18.04 (`bionic`), newest distro for Travis seems to be `xenial` (16.04).

**Comment by rix0rrr** [comment]
Yay it workses!

**Comment by skinny85** [comment]
Thanks for picking this up Rico!

**Pull request merged**
