### PR TITLE
feat: Add typescript assertions examples to lambda-cron

### PR DESCRIPTION
**Pull request by kaizen3031593**
This PR adds a suite of tests to the `lambda-cron` example in Typescript. It serves to demonstrate how to use the new [`assertions`](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/assertions) library. In a separate PR, I will introduce similar testing capabilities in other JSII target languages.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license].

[Apache 2.0 license]: https://www.apache.org/licenses/LICENSE-2.0

### CODE REVIEW

**Review by nija-at — COMMENTED** [review]
This looks fantastic 😊

Also add a 'testing' section to the readme - https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/lambda-cron

**Comment by kaizen3031593** [comment]
Updated the readme. The rest of this PR is waiting for CDK v1.123 to be released so I will circle back later this week.

**Comment by nija-at** [comment]
Are you thinking of adding assertions for other languages as part of this PR or a separate PR?

**Comment by kaizen3031593** [comment]
I suppose it makes more sense to do separate PRs. At any rate I will wait for 1.123 for `Capture` and `Match.anyValue()` support before removing draft status and requesting a final review.

**Review by ryparker — APPROVED** [review]

**Pull request merged**
